### ISSUE TITLE
PHP Warning ModuleVisitorsTag.php on line 666 

### ISSUE THREAD

**Issue by BugBuster1701** [BugBuster1701/visitors#199]
Contao 3.5.6 mit Composer-Client
PHP 5.6.12
Visitors 3.6.0

```
PHP Warning: Creating default object from empty value in /homepages/contao/system/modules/visitors/classes/ModuleVisitorsTag.php on line 666
#0 /homepages/contao/system/modules/visitors/classes/ModuleVisitorsTag.php(666): __error(2, 'Creating defaul...', '/homepages/c...', 666, Array)
#1 /homepages/contao/system/modules/visitors/classes/ModuleVisitorsTag.php(127): BugBuster\Visitors\ModuleVisitorsTag->visitorCountUpdate('1', '1800', 1)
#2 /homepages/contao/system/modules/core/library/Contao/InsertTags.php(1139): BugBuster\Visitors\ModuleVisitorsTag->replaceInsertTagsVisitors('cache_visitors:...', false, '', Array, Array, Array, 6, 10)
#3 /homepages/contao/system/modules/core/library/Contao/Controller.php(686): Contao\InsertTags->replace('<!DOCTYPE html>...', false)
#4 /homepages/contao/system/modules/core/controllers/FrontendIndex.php(459): Contao\Controller::replaceInsertTags('<!DOCTYPE html>...', false)
#5 /homepages/contao/system/modules/core/controllers/FrontendIndex.php(28): Contao\FrontendIndex->outputFromCache()
#6 /homepages/contao/index.php(19): Contao\FrontendIndex->__construct()
#7 {main}
```

[Forum](https://community.contao.org/de/showthread.php?61053-PHP-Warning-ModuleVisitorsTag-php-on-line-666)

**Comment by BugBuster1701** [comment]
testen bei unbekannten Seiten Typ bei autoitems (FAQ, NEWS, ...)

**Comment by BugBuster1701** [comment]
Bei mir nun auch ein Mal. Debugging eingeschaltet für VisitorTag.
Eingeschaltet war nur für SearchEngine:

```
[17-Aug-2016 17:09:29] [29624613] [## START ##] [## DEBUG ##] T0#C0#R0#S1
[17-Aug-2016 17:09:29] [29624613] [ModuleVisitorSearchEngine::checkEngines] [127] 
Engine Name : unknown
Keywords    : unknown
```

**Comment by BugBuster1701** [comment]
System-Log:
```
No active page for page ID "news", host "contao.ninja" and languages "de, en-US, en" (https://contao.ninja/news.html)
Funktion: 	Contao\PageError404::generate
IP-Adresse: 	217.89.39.0
Browser: 	Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:47.0) Gecko/20100101 Firefox/47.0
```
Die Seite gibt es wirklich nicht.

**Comment by BugBuster1701** [comment]
```
/**
 * Page types
 */
$GLOBALS['TL_PTY'] = array
(
	'regular'   => 'PageRegular',
	'forward'   => 'PageForward',
	'redirect'  => 'PageRedirect',
	'root'      => 'PageRoot',
	'error_403' => 'PageError403',
	'error_404' => 'PageError404'
);
```

**Comment by BugBuster1701** [comment]
Wenn 404 Seite aus dem Cache kommt, dann ergibt es diesen Fehler. Bei abgeschaltetem Cache nicht.
Erster Log ohne Cache, zweiter mit Cache:
```
[25-Aug-2016 22:31:38] [97368407] [## START ##] [## DEBUG ##] T1#C1#R1#S0
[25-Aug-2016 22:31:38] [97368407] [ModuleVisitorsTag::replaceInsertTagsVisitors] [203] :start
[25-Aug-2016 22:31:38] [97368407] [ModuleVisitorChecks::checkBot] [56] : False
[25-Aug-2016 22:31:38] [97368407] [ModuleVisitorChecks::checkBE] [127] : False
[25-Aug-2016 22:31:38] [97368407] [ModuleVisitorsTag::visitorCountUpdate] [658] Page ID / Lang in Object: 19 / en
[25-Aug-2016 22:31:38] [97368407] [ModuleVisitorsTag::visitorGetPageType] [1021] PageType: 0
[25-Aug-2016 22:31:38] [97368407] [ModuleVisitorsTag::visitorGetPageIdByType] [1071] PageIdNormal: 19
[25-Aug-2016 22:31:38] [97368407] [ModuleVisitorsTag::replaceInsertTagsVisitors] [139] Counted Server: True
[25-Aug-2016 22:31:38] [97368407] [ModuleVisitorsTag::replaceInsertTagsVisitors] [183] :name
[25-Aug-2016 22:31:38] [97368407] [ModuleVisitorsTag::replaceInsertTagsVisitors] [188] :online
[25-Aug-2016 22:31:38] [97368407] [ModuleVisitorsTag::replaceInsertTagsVisitors] [255] :todayvisit
[25-Aug-2016 22:31:38] [97368407] [ModuleVisitorsTag::replaceInsertTagsVisitors] [217] :totalvisit
[25-Aug-2016 22:31:38] [97368407] [ModuleVisitorsTag::replaceInsertTagsVisitors] [277] :todayhit
[25-Aug-2016 22:31:38] [97368407] [ModuleVisitorsTag::replaceInsertTagsVisitors] [236] :totalhit
[25-Aug-2016 22:31:38] [97368407] [ModuleVisitorsTag::replaceInsertTagsVisitors] [299] :averagevisits
[25-Aug-2016 22:31:38] [97368407] [ModuleVisitorsTag::replaceInsertTagsVisitors] [203] :start


[25-Aug-2016 22:31:45] [26249729] [## START ##] [## DEBUG ##] T1#C1#R1#S0
[25-Aug-2016 22:31:45] [26249729] [ModuleVisitorChecks::checkBot] [56] : False
[25-Aug-2016 22:31:45] [26249729] [ModuleVisitorChecks::checkBE] [127] : False
[25-Aug-2016 22:31:45] [26249729] [ModuleVisitorsTag::visitorCountUpdate] [599] Page ID over URL: navigation2
[25-Aug-2016 22:31:45] [26249729] [ModuleVisitorsTag::visitorCountUpdate] [658] Page ID / Lang in Object:  / 
[25-Aug-2016 22:31:45] [26249729] [ModuleVisitorsTag::visitorGetPageType] [1021] PageType: 0
[25-Aug-2016 22:31:45] [26249729] [ModuleVisitorsTag::visitorGetPageIdByType] [1071] PageIdNormal: 
[25-Aug-2016 22:31:45] [26249729] [ModuleVisitorsTag::replaceInsertTagsVisitors] [139] Counted Server: True
[25-Aug-2016 22:31:45] [26249729] [ModuleVisitorsTag::replaceInsertTagsVisitors] [183] :name
[25-Aug-2016 22:31:45] [26249729] [ModuleVisitorsTag::replaceInsertTagsVisitors] [188] :online
[25-Aug-2016 22:31:45] [26249729] [ModuleVisitorsTag::replaceInsertTagsVisitors] [255] :todayvisit
[25-Aug-2016 22:31:45] [26249729] [ModuleVisitorsTag::replaceInsertTagsVisitors] [217] :totalvisit
[25-Aug-2016 22:31:45] [26249729] [ModuleVisitorsTag::replaceInsertTagsVisitors] [277] :todayhit
[25-Aug-2016 22:31:45] [26249729] [ModuleVisitorsTag::replaceInsertTagsVisitors] [236] :totalhit
[25-Aug-2016 22:31:45] [26249729] [ModuleVisitorsTag::replaceInsertTagsVisitors] [299] :averagevisits
```
error.log
```[25-Aug-2016 22:31:45 Europe/Berlin] 
PHP Warning: Creating default object from empty value in /daten/contao2go/vhosts/contao35_develop/system/modules/visitors/classes/ModuleVisitorsTag.php on line 666
#0 system/modules/visitors/classes/ModuleVisitorsTag.php(666): __error_enhanced(2, 'Creating default object from empty value', 'system/modules/visitors/classes/ModuleVisitorsTag.php', 666, Array)
#1 system/modules/visitors/classes/ModuleVisitorsTag.php(127): BugBuster\Visitors\ModuleVisitorsTag->visitorCountUpdate('1', '1800', 1)
#2 system/modules/core/library/Contao/InsertTags.php(1129): BugBuster\Visitors\ModuleVisitorsTag->replaceInsertTagsVisitors('cache_visitors::1::count', false, '', Array, Array, Array, 6, 34)
#3 system/modules/core/library/Contao/Controller.php(692): Contao\InsertTags->replace('<!DOCTYPE html>
<html lang="en">
<head>
...
</body>
</html>
', false)
#5 system/modules/core/controllers/FrontendIndex.php(28): Contao\FrontendIndex->outputFromCache()
#6 index.php(19): Contao\FrontendIndex->__construct()

```

**Comment by BugBuster1701** [comment]
Extra Behandlung:
* [ ] 404 Seite
* [ ] 403 Seite
